# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5778abc0e2e69c86219b867d52bf3b5b933b8d9447db14235d83578aa4481c07a1d83b2c78a5cfb25698c6937fc6fb3c652d3416b6ffa79875d7e2a27a6f5468

test:
  secret_key_base: bc35c4f7eec75f6faa42ec80bc53a00007ffc24ffd52de98ffa6d87baca897a28ec65e3c918c2609a2d6d50d54946d34361870ce73e39e26e67da141764aa04f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
